package domain.shared;

public enum MonitoringZustand {

	RECEIVED, SCANNED, CONTAINER_FETCHED, TRANSPORTED_TO_HBW, TRANSPORTED_TO_STOCKPLACE, STORED, ORDERED, BOOKED_OUT,
	TRANSPORTED_TO_MPO, IN_PROCESS, PROCESSED, TRANSPORTED_TO_DSO, TRANSPORTED_TO_OUT, SHIPPED

}
